package com.nasportfolio.test.tags

object TestTags {
    const val LOGIN_BUTTON = "LOGIN_BUTTON"
    const val EMAIL_INPUT = "EMAIL_INPUT"
    const val PASSWORD_INPUT = "PASSWORD_INPUT"
    const val FAVORITE_RESTAURANT_TAG = "FAVORITE_RESTAURANT_TAG"
    const val FEATURED_RESTAURANT_TAG = "FEATURED_RESTAURANT_TAG"
    const val ALL_RESTAURANTS_TAG = "ALL_RESTAURANTS_TAG"
    const val FAVORITE_BTN = "FAVORITE_BTN"
    const val LAZY_COLUMN = "LAZY_COLUMN"
    const val ADD_RESTAURANT_FAB = "ADD_RESTAURANT_FAB"
    const val BOTTOM_NAV_HOME = "BOTTOM_NAV_HOME"
    const val BOTTOM_NAV_SEARCH = "BOTTOM_NAV_SEARCH"
    const val BOTTOM_NAV_PROFILE = "BOTTOM_NAV_PROFILE"
    const val LOG_OUT_BTN = "LOG_OUT_BTN"
    const val EDIT_PROFILE_BTN = "EDIT_PROFILE_BTN"
    const val USERNAME_INPUT = "USERNAME_INPUT"
    const val UPDATE_ACCOUNT_BTN = "UPDATE_ACCOUNT_BTN"
}